version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-6gh6%1716l3dn2@fnbw^u%#3*g&3q9_q8$2lcsq^l8cj6bcqli
      - DATABASE_URL=postgres://dbuser:dbpassword@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=dbname
